version: 0.0
os: linux
files:
	- source: /
	  destination: /home/ubuntu/webpage
hooks:
	ApplicationStop:
		- location: scripts/stop.sh
		  timeout: 300
		  runas: root
	ApplicationStart:
		- location: scripts/run.sh
		  timeout: 300
		  runas: root
